server:
  port: 9600

spring:
  data:
    mongodb:
      uri: mongodb://app:1234@localhost:27017/seeyouletter

aws:
  endpoint: http://127.0.0.1:4566
  s3:
    region: local

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG