version: '3.9'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: s3
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
  postgresql:
    image: postgres:14.5-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: seeyouletter
    volumes:
      - ~/docker/postgresql/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: seeyouletter
    volumes:
      - ~/docker/mongo/data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  redis:
    image: redis:7.0.5
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ~/docker/redis/data:/data


