#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# skip if merge commit
if [ "${COMMIT_SOURCE}" = merge ];then
    exit 0
fi

exec < /dev/tty && node_modules/.bin/cz --hook || true