server:
  port: 8600
  forward-headers-strategy: native

spring:
  datasource:
    url: ENC(XtqMO6KzspZXczHkLSg5qATICavsuQrK/mVCyfzmCpR3D9myQPVIAxQ7y6njtz/Cq01VtCTL/7FNymNNuFBLCnPNvFWdjGepFJ53pGvpiaX1QAejvomzPVKN5MAppTj8YjVmVBL4xhJjijB+VLg5jITRaiRzsZPPas+gAFq/GbHPJjD5jqYkXKTjyjY/ODt0fhvszJspLms4TpllK+TZjTjZM5DlG8PLL0ny2Ih8bKitps+6JvB4jA==)
    username: ENC(JSLUGXjwqAjx5qhMQhpQvoCb1ezUg/EF)
    password: ENC(VQNpUTFSOAhEaLNcRbrzR0kDHSc2fJyNarbtjYEeU6I=)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  redis:
    host: ENC(c9oB4rht7QricGx0PBvgEhaEqd829uenF5X24wqHBRvQtuWEiT1NYpWHB7K6sqLtgj/XdO9Rzz49OsDhhQ3PIc9KzR3h6ieIsXCEA54BGrz+lcVtpy558A==)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port}
      client:
        registration:
          naver:
            clientId: g0bylVi7uVVNgMMZLVDM
            clientSecret: ENC(8bcU3cyY5Q2MX5f+S9ThJiNJ7e4ghBhJ)
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: https://dev-member.seeyouletter.kr/login/oauth2/code/naver
            scope:
              - nickname
              - email
              - profile_image
              - gender
              - birthyear
              - birthday
              - mobile
            clientName: Naver
          kakao:
            clientId: e860223901e9152978e1ec2754505445
            clientSecret: ENC(1I/cNlCx47qp0++4yLUpsPZ2rVEhNCN9n1MI4pMlN0Ez0nToUbhtuMAgBVpmb7Dv)
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: https://dev-member.seeyouletter.kr/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
              - gender
              - birthday
            clientName: Kakao

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

first:
  party:
    client:
      origins:
        - http://localhost:2462
        - http://127.0.0.1:2462
        - https://seeyouletter.kr
        - https://www.seeyouletter.kr

aws:
  s3:
    region: ap-northeast-2

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.jackson2: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE